#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_email_feature_platform_statistics

type Feature* {.pure.} = enum
  Amp
  CssAccentColor
  CssAlignItems
  CssAnimation
  CssAspectRatio
  CssAtFontFace
  CssAtImport
  CssAtKeyframes
  CssAtMedia
  CssAtSupports
  CssBackgroundBlendMode
  CssBackgroundClip
  CssBackgroundColor
  CssBackgroundImage
  CssBackgroundOrigin
  CssBackgroundPosition
  CssBackgroundRepeat
  CssBackgroundSize
  CssBackground
  CssBlockInlineSize
  CssBorderImage
  CssBorderInlineBlockIndividual
  CssBorderInlineBlockLonghand
  CssBorderInlineBlock
  CssBorderRadiusLogical
  CssBorderRadius
  CssBorder
  CssBoxShadow
  CssBoxSizing
  CssCaptionSide
  CssClipPath
  CssColumnCount
  CssColumnLayoutProperties
  CssDirection
  CssDisplayFlex
  CssDisplayGrid
  CssDisplayNone
  CssDisplay
  CssFilter
  CssFlexDirection
  CssFlexWrap
  CssFloat
  CssFontKerning
  CssFontWeight
  CssFont
  CssGap
  CssGridTemplate
  CssHeight
  CssHyphens
  CssInlineSize
  CssJustifyContent
  CssLeftRightTopBottom
  CssLetterSpacing
  CssLineHeight
  CssListStyleImage
  CssListStylePosition
  CssListStyleType
  CssListStyle
  CssMarginBlockStartEnd
  CssMarginInlineBlock
  CssMarginInlineStartEnd
  CssMarginInline
  CssMargin
  CssMaxBlockSize
  CssMaxHeight
  CssMaxWidth
  CssMinHeight
  CssMinInlineSize
  CssMinWidth
  CssMixBlendMode
  CssObjectFit
  CssObjectPosition
  CssOpacity
  CssOutlineOffset
  CssOutline
  CssOverflowWrap
  CssOverflow
  CssPaddingBlockStartEnd
  CssPaddingInlineBlock
  CssPaddingInlineStartEnd
  CssPadding
  CssPosition
  CssTabSize
  CssTableLayout
  CssTextAlignLast
  CssTextAlign
  CssTextDecorationColor
  CssTextDecorationThickness
  CssTextDecoration
  CssTextEmphasisPosition
  CssTextEmphasis
  CssTextIndent
  CssTextOverflow
  CssTextShadow
  CssTextTransform
  CssTextUnderlineOffset
  CssTransform
  CssVerticalAlign
  CssVisibility
  CssWhiteSpace
  CssWidth
  CssWordBreak
  CssWritingMode
  CssZIndex
  HtmlAbbr
  HtmlAddress
  HtmlAlign
  HtmlAnchorLinks
  HtmlAriaDescribedby
  HtmlAriaHidden
  HtmlAriaLabel
  HtmlAriaLabelledby
  HtmlAriaLive
  HtmlAudio
  HtmlBackground
  HtmlBase
  HtmlBlockquote
  HtmlBody
  HtmlButtonReset
  HtmlButtonSubmit
  HtmlCode
  HtmlDel
  HtmlDfn
  HtmlDialog
  HtmlDir
  HtmlDiv
  HtmlDoctype
  HtmlForm
  HtmlH1H6
  HtmlHeight
  HtmlImageMaps
  HtmlInputCheckbox
  HtmlInputHidden
  HtmlInputRadio
  HtmlInputReset
  HtmlInputSubmit
  HtmlInputText
  HtmlLang
  HtmlLink
  HtmlLists
  HtmlLoadingAttribute
  HtmlMailtoLinks
  HtmlMarquee
  HtmlMeter
  HtmlObject
  HtmlP
  HtmlPicture
  HtmlPre
  HtmlProgress
  HtmlRequired
  HtmlRole
  HtmlRp
  HtmlRt
  HtmlRuby
  HtmlSelect
  HtmlSemantics
  HtmlSmall
  HtmlSpan
  HtmlSrcset
  HtmlStrike
  HtmlStrong
  HtmlStyle
  HtmlSvg
  HtmlTable
  HtmlTarget
  HtmlTextarea
  HtmlValign
  HtmlVideo
  HtmlWbr
  HtmlWidth
  ImageAvif
  ImageBase64
  ImageBmp
  ImageGif
  ImageIco
  ImageJpg
  ImagePng
  ImageSvg
  ImageWebp
  Unsupported

type Family* {.pure.} = enum
  Aol
  AppleMail
  Fastmail
  FreeFr
  Gmail
  Gmx
  Hey
  Ionos1and1
  Laposte
  MailRu
  Microsoft
  Orange
  Outlook
  Protonmail
  Rainloop
  SamsungEmail
  Sfr
  TOnlineDe
  Thunderbird
  WebDe
  Yahoo

type EmailFeatureFamilyStatistics* = object
  ## 
  feature*: Feature
  family*: Family
  platforms*: seq[EmailFeaturePlatformStatistics]

func `%`*(v: Feature): JsonNode =
  let str = case v:
    of Feature.Amp: "amp"
    of Feature.CssAccentColor: "css-accent-color"
    of Feature.CssAlignItems: "css-align-items"
    of Feature.CssAnimation: "css-animation"
    of Feature.CssAspectRatio: "css-aspect-ratio"
    of Feature.CssAtFontFace: "css-at-font-face"
    of Feature.CssAtImport: "css-at-import"
    of Feature.CssAtKeyframes: "css-at-keyframes"
    of Feature.CssAtMedia: "css-at-media"
    of Feature.CssAtSupports: "css-at-supports"
    of Feature.CssBackgroundBlendMode: "css-background-blend-mode"
    of Feature.CssBackgroundClip: "css-background-clip"
    of Feature.CssBackgroundColor: "css-background-color"
    of Feature.CssBackgroundImage: "css-background-image"
    of Feature.CssBackgroundOrigin: "css-background-origin"
    of Feature.CssBackgroundPosition: "css-background-position"
    of Feature.CssBackgroundRepeat: "css-background-repeat"
    of Feature.CssBackgroundSize: "css-background-size"
    of Feature.CssBackground: "css-background"
    of Feature.CssBlockInlineSize: "css-block-inline-size"
    of Feature.CssBorderImage: "css-border-image"
    of Feature.CssBorderInlineBlockIndividual: "css-border-inline-block-individual"
    of Feature.CssBorderInlineBlockLonghand: "css-border-inline-block-longhand"
    of Feature.CssBorderInlineBlock: "css-border-inline-block"
    of Feature.CssBorderRadiusLogical: "css-border-radius-logical"
    of Feature.CssBorderRadius: "css-border-radius"
    of Feature.CssBorder: "css-border"
    of Feature.CssBoxShadow: "css-box-shadow"
    of Feature.CssBoxSizing: "css-box-sizing"
    of Feature.CssCaptionSide: "css-caption-side"
    of Feature.CssClipPath: "css-clip-path"
    of Feature.CssColumnCount: "css-column-count"
    of Feature.CssColumnLayoutProperties: "css-column-layout-properties"
    of Feature.CssDirection: "css-direction"
    of Feature.CssDisplayFlex: "css-display-flex"
    of Feature.CssDisplayGrid: "css-display-grid"
    of Feature.CssDisplayNone: "css-display-none"
    of Feature.CssDisplay: "css-display"
    of Feature.CssFilter: "css-filter"
    of Feature.CssFlexDirection: "css-flex-direction"
    of Feature.CssFlexWrap: "css-flex-wrap"
    of Feature.CssFloat: "css-float"
    of Feature.CssFontKerning: "css-font-kerning"
    of Feature.CssFontWeight: "css-font-weight"
    of Feature.CssFont: "css-font"
    of Feature.CssGap: "css-gap"
    of Feature.CssGridTemplate: "css-grid-template"
    of Feature.CssHeight: "css-height"
    of Feature.CssHyphens: "css-hyphens"
    of Feature.CssInlineSize: "css-inline-size"
    of Feature.CssJustifyContent: "css-justify-content"
    of Feature.CssLeftRightTopBottom: "css-left-right-top-bottom"
    of Feature.CssLetterSpacing: "css-letter-spacing"
    of Feature.CssLineHeight: "css-line-height"
    of Feature.CssListStyleImage: "css-list-style-image"
    of Feature.CssListStylePosition: "css-list-style-position"
    of Feature.CssListStyleType: "css-list-style-type"
    of Feature.CssListStyle: "css-list-style"
    of Feature.CssMarginBlockStartEnd: "css-margin-block-start-end"
    of Feature.CssMarginInlineBlock: "css-margin-inline-block"
    of Feature.CssMarginInlineStartEnd: "css-margin-inline-start-end"
    of Feature.CssMarginInline: "css-margin-inline"
    of Feature.CssMargin: "css-margin"
    of Feature.CssMaxBlockSize: "css-max-block-size"
    of Feature.CssMaxHeight: "css-max-height"
    of Feature.CssMaxWidth: "css-max-width"
    of Feature.CssMinHeight: "css-min-height"
    of Feature.CssMinInlineSize: "css-min-inline-size"
    of Feature.CssMinWidth: "css-min-width"
    of Feature.CssMixBlendMode: "css-mix-blend-mode"
    of Feature.CssObjectFit: "css-object-fit"
    of Feature.CssObjectPosition: "css-object-position"
    of Feature.CssOpacity: "css-opacity"
    of Feature.CssOutlineOffset: "css-outline-offset"
    of Feature.CssOutline: "css-outline"
    of Feature.CssOverflowWrap: "css-overflow-wrap"
    of Feature.CssOverflow: "css-overflow"
    of Feature.CssPaddingBlockStartEnd: "css-padding-block-start-end"
    of Feature.CssPaddingInlineBlock: "css-padding-inline-block"
    of Feature.CssPaddingInlineStartEnd: "css-padding-inline-start-end"
    of Feature.CssPadding: "css-padding"
    of Feature.CssPosition: "css-position"
    of Feature.CssTabSize: "css-tab-size"
    of Feature.CssTableLayout: "css-table-layout"
    of Feature.CssTextAlignLast: "css-text-align-last"
    of Feature.CssTextAlign: "css-text-align"
    of Feature.CssTextDecorationColor: "css-text-decoration-color"
    of Feature.CssTextDecorationThickness: "css-text-decoration-thickness"
    of Feature.CssTextDecoration: "css-text-decoration"
    of Feature.CssTextEmphasisPosition: "css-text-emphasis-position"
    of Feature.CssTextEmphasis: "css-text-emphasis"
    of Feature.CssTextIndent: "css-text-indent"
    of Feature.CssTextOverflow: "css-text-overflow"
    of Feature.CssTextShadow: "css-text-shadow"
    of Feature.CssTextTransform: "css-text-transform"
    of Feature.CssTextUnderlineOffset: "css-text-underline-offset"
    of Feature.CssTransform: "css-transform"
    of Feature.CssVerticalAlign: "css-vertical-align"
    of Feature.CssVisibility: "css-visibility"
    of Feature.CssWhiteSpace: "css-white-space"
    of Feature.CssWidth: "css-width"
    of Feature.CssWordBreak: "css-word-break"
    of Feature.CssWritingMode: "css-writing-mode"
    of Feature.CssZIndex: "css-z-index"
    of Feature.HtmlAbbr: "html-abbr"
    of Feature.HtmlAddress: "html-address"
    of Feature.HtmlAlign: "html-align"
    of Feature.HtmlAnchorLinks: "html-anchor-links"
    of Feature.HtmlAriaDescribedby: "html-aria-describedby"
    of Feature.HtmlAriaHidden: "html-aria-hidden"
    of Feature.HtmlAriaLabel: "html-aria-label"
    of Feature.HtmlAriaLabelledby: "html-aria-labelledby"
    of Feature.HtmlAriaLive: "html-aria-live"
    of Feature.HtmlAudio: "html-audio"
    of Feature.HtmlBackground: "html-background"
    of Feature.HtmlBase: "html-base"
    of Feature.HtmlBlockquote: "html-blockquote"
    of Feature.HtmlBody: "html-body"
    of Feature.HtmlButtonReset: "html-button-reset"
    of Feature.HtmlButtonSubmit: "html-button-submit"
    of Feature.HtmlCode: "html-code"
    of Feature.HtmlDel: "html-del"
    of Feature.HtmlDfn: "html-dfn"
    of Feature.HtmlDialog: "html-dialog"
    of Feature.HtmlDir: "html-dir"
    of Feature.HtmlDiv: "html-div"
    of Feature.HtmlDoctype: "html-doctype"
    of Feature.HtmlForm: "html-form"
    of Feature.HtmlH1H6: "html-h1-h6"
    of Feature.HtmlHeight: "html-height"
    of Feature.HtmlImageMaps: "html-image-maps"
    of Feature.HtmlInputCheckbox: "html-input-checkbox"
    of Feature.HtmlInputHidden: "html-input-hidden"
    of Feature.HtmlInputRadio: "html-input-radio"
    of Feature.HtmlInputReset: "html-input-reset"
    of Feature.HtmlInputSubmit: "html-input-submit"
    of Feature.HtmlInputText: "html-input-text"
    of Feature.HtmlLang: "html-lang"
    of Feature.HtmlLink: "html-link"
    of Feature.HtmlLists: "html-lists"
    of Feature.HtmlLoadingAttribute: "html-loading-attribute"
    of Feature.HtmlMailtoLinks: "html-mailto-links"
    of Feature.HtmlMarquee: "html-marquee"
    of Feature.HtmlMeter: "html-meter"
    of Feature.HtmlObject: "html-object"
    of Feature.HtmlP: "html-p"
    of Feature.HtmlPicture: "html-picture"
    of Feature.HtmlPre: "html-pre"
    of Feature.HtmlProgress: "html-progress"
    of Feature.HtmlRequired: "html-required"
    of Feature.HtmlRole: "html-role"
    of Feature.HtmlRp: "html-rp"
    of Feature.HtmlRt: "html-rt"
    of Feature.HtmlRuby: "html-ruby"
    of Feature.HtmlSelect: "html-select"
    of Feature.HtmlSemantics: "html-semantics"
    of Feature.HtmlSmall: "html-small"
    of Feature.HtmlSpan: "html-span"
    of Feature.HtmlSrcset: "html-srcset"
    of Feature.HtmlStrike: "html-strike"
    of Feature.HtmlStrong: "html-strong"
    of Feature.HtmlStyle: "html-style"
    of Feature.HtmlSvg: "html-svg"
    of Feature.HtmlTable: "html-table"
    of Feature.HtmlTarget: "html-target"
    of Feature.HtmlTextarea: "html-textarea"
    of Feature.HtmlValign: "html-valign"
    of Feature.HtmlVideo: "html-video"
    of Feature.HtmlWbr: "html-wbr"
    of Feature.HtmlWidth: "html-width"
    of Feature.ImageAvif: "image-avif"
    of Feature.ImageBase64: "image-base64"
    of Feature.ImageBmp: "image-bmp"
    of Feature.ImageGif: "image-gif"
    of Feature.ImageIco: "image-ico"
    of Feature.ImageJpg: "image-jpg"
    of Feature.ImagePng: "image-png"
    of Feature.ImageSvg: "image-svg"
    of Feature.ImageWebp: "image-webp"
    of Feature.Unsupported: "unsupported"

  JsonNode(kind: JString, str: str)

func `$`*(v: Feature): string =
  result = case v:
    of Feature.Amp: "amp"
    of Feature.CssAccentColor: "css-accent-color"
    of Feature.CssAlignItems: "css-align-items"
    of Feature.CssAnimation: "css-animation"
    of Feature.CssAspectRatio: "css-aspect-ratio"
    of Feature.CssAtFontFace: "css-at-font-face"
    of Feature.CssAtImport: "css-at-import"
    of Feature.CssAtKeyframes: "css-at-keyframes"
    of Feature.CssAtMedia: "css-at-media"
    of Feature.CssAtSupports: "css-at-supports"
    of Feature.CssBackgroundBlendMode: "css-background-blend-mode"
    of Feature.CssBackgroundClip: "css-background-clip"
    of Feature.CssBackgroundColor: "css-background-color"
    of Feature.CssBackgroundImage: "css-background-image"
    of Feature.CssBackgroundOrigin: "css-background-origin"
    of Feature.CssBackgroundPosition: "css-background-position"
    of Feature.CssBackgroundRepeat: "css-background-repeat"
    of Feature.CssBackgroundSize: "css-background-size"
    of Feature.CssBackground: "css-background"
    of Feature.CssBlockInlineSize: "css-block-inline-size"
    of Feature.CssBorderImage: "css-border-image"
    of Feature.CssBorderInlineBlockIndividual: "css-border-inline-block-individual"
    of Feature.CssBorderInlineBlockLonghand: "css-border-inline-block-longhand"
    of Feature.CssBorderInlineBlock: "css-border-inline-block"
    of Feature.CssBorderRadiusLogical: "css-border-radius-logical"
    of Feature.CssBorderRadius: "css-border-radius"
    of Feature.CssBorder: "css-border"
    of Feature.CssBoxShadow: "css-box-shadow"
    of Feature.CssBoxSizing: "css-box-sizing"
    of Feature.CssCaptionSide: "css-caption-side"
    of Feature.CssClipPath: "css-clip-path"
    of Feature.CssColumnCount: "css-column-count"
    of Feature.CssColumnLayoutProperties: "css-column-layout-properties"
    of Feature.CssDirection: "css-direction"
    of Feature.CssDisplayFlex: "css-display-flex"
    of Feature.CssDisplayGrid: "css-display-grid"
    of Feature.CssDisplayNone: "css-display-none"
    of Feature.CssDisplay: "css-display"
    of Feature.CssFilter: "css-filter"
    of Feature.CssFlexDirection: "css-flex-direction"
    of Feature.CssFlexWrap: "css-flex-wrap"
    of Feature.CssFloat: "css-float"
    of Feature.CssFontKerning: "css-font-kerning"
    of Feature.CssFontWeight: "css-font-weight"
    of Feature.CssFont: "css-font"
    of Feature.CssGap: "css-gap"
    of Feature.CssGridTemplate: "css-grid-template"
    of Feature.CssHeight: "css-height"
    of Feature.CssHyphens: "css-hyphens"
    of Feature.CssInlineSize: "css-inline-size"
    of Feature.CssJustifyContent: "css-justify-content"
    of Feature.CssLeftRightTopBottom: "css-left-right-top-bottom"
    of Feature.CssLetterSpacing: "css-letter-spacing"
    of Feature.CssLineHeight: "css-line-height"
    of Feature.CssListStyleImage: "css-list-style-image"
    of Feature.CssListStylePosition: "css-list-style-position"
    of Feature.CssListStyleType: "css-list-style-type"
    of Feature.CssListStyle: "css-list-style"
    of Feature.CssMarginBlockStartEnd: "css-margin-block-start-end"
    of Feature.CssMarginInlineBlock: "css-margin-inline-block"
    of Feature.CssMarginInlineStartEnd: "css-margin-inline-start-end"
    of Feature.CssMarginInline: "css-margin-inline"
    of Feature.CssMargin: "css-margin"
    of Feature.CssMaxBlockSize: "css-max-block-size"
    of Feature.CssMaxHeight: "css-max-height"
    of Feature.CssMaxWidth: "css-max-width"
    of Feature.CssMinHeight: "css-min-height"
    of Feature.CssMinInlineSize: "css-min-inline-size"
    of Feature.CssMinWidth: "css-min-width"
    of Feature.CssMixBlendMode: "css-mix-blend-mode"
    of Feature.CssObjectFit: "css-object-fit"
    of Feature.CssObjectPosition: "css-object-position"
    of Feature.CssOpacity: "css-opacity"
    of Feature.CssOutlineOffset: "css-outline-offset"
    of Feature.CssOutline: "css-outline"
    of Feature.CssOverflowWrap: "css-overflow-wrap"
    of Feature.CssOverflow: "css-overflow"
    of Feature.CssPaddingBlockStartEnd: "css-padding-block-start-end"
    of Feature.CssPaddingInlineBlock: "css-padding-inline-block"
    of Feature.CssPaddingInlineStartEnd: "css-padding-inline-start-end"
    of Feature.CssPadding: "css-padding"
    of Feature.CssPosition: "css-position"
    of Feature.CssTabSize: "css-tab-size"
    of Feature.CssTableLayout: "css-table-layout"
    of Feature.CssTextAlignLast: "css-text-align-last"
    of Feature.CssTextAlign: "css-text-align"
    of Feature.CssTextDecorationColor: "css-text-decoration-color"
    of Feature.CssTextDecorationThickness: "css-text-decoration-thickness"
    of Feature.CssTextDecoration: "css-text-decoration"
    of Feature.CssTextEmphasisPosition: "css-text-emphasis-position"
    of Feature.CssTextEmphasis: "css-text-emphasis"
    of Feature.CssTextIndent: "css-text-indent"
    of Feature.CssTextOverflow: "css-text-overflow"
    of Feature.CssTextShadow: "css-text-shadow"
    of Feature.CssTextTransform: "css-text-transform"
    of Feature.CssTextUnderlineOffset: "css-text-underline-offset"
    of Feature.CssTransform: "css-transform"
    of Feature.CssVerticalAlign: "css-vertical-align"
    of Feature.CssVisibility: "css-visibility"
    of Feature.CssWhiteSpace: "css-white-space"
    of Feature.CssWidth: "css-width"
    of Feature.CssWordBreak: "css-word-break"
    of Feature.CssWritingMode: "css-writing-mode"
    of Feature.CssZIndex: "css-z-index"
    of Feature.HtmlAbbr: "html-abbr"
    of Feature.HtmlAddress: "html-address"
    of Feature.HtmlAlign: "html-align"
    of Feature.HtmlAnchorLinks: "html-anchor-links"
    of Feature.HtmlAriaDescribedby: "html-aria-describedby"
    of Feature.HtmlAriaHidden: "html-aria-hidden"
    of Feature.HtmlAriaLabel: "html-aria-label"
    of Feature.HtmlAriaLabelledby: "html-aria-labelledby"
    of Feature.HtmlAriaLive: "html-aria-live"
    of Feature.HtmlAudio: "html-audio"
    of Feature.HtmlBackground: "html-background"
    of Feature.HtmlBase: "html-base"
    of Feature.HtmlBlockquote: "html-blockquote"
    of Feature.HtmlBody: "html-body"
    of Feature.HtmlButtonReset: "html-button-reset"
    of Feature.HtmlButtonSubmit: "html-button-submit"
    of Feature.HtmlCode: "html-code"
    of Feature.HtmlDel: "html-del"
    of Feature.HtmlDfn: "html-dfn"
    of Feature.HtmlDialog: "html-dialog"
    of Feature.HtmlDir: "html-dir"
    of Feature.HtmlDiv: "html-div"
    of Feature.HtmlDoctype: "html-doctype"
    of Feature.HtmlForm: "html-form"
    of Feature.HtmlH1H6: "html-h1-h6"
    of Feature.HtmlHeight: "html-height"
    of Feature.HtmlImageMaps: "html-image-maps"
    of Feature.HtmlInputCheckbox: "html-input-checkbox"
    of Feature.HtmlInputHidden: "html-input-hidden"
    of Feature.HtmlInputRadio: "html-input-radio"
    of Feature.HtmlInputReset: "html-input-reset"
    of Feature.HtmlInputSubmit: "html-input-submit"
    of Feature.HtmlInputText: "html-input-text"
    of Feature.HtmlLang: "html-lang"
    of Feature.HtmlLink: "html-link"
    of Feature.HtmlLists: "html-lists"
    of Feature.HtmlLoadingAttribute: "html-loading-attribute"
    of Feature.HtmlMailtoLinks: "html-mailto-links"
    of Feature.HtmlMarquee: "html-marquee"
    of Feature.HtmlMeter: "html-meter"
    of Feature.HtmlObject: "html-object"
    of Feature.HtmlP: "html-p"
    of Feature.HtmlPicture: "html-picture"
    of Feature.HtmlPre: "html-pre"
    of Feature.HtmlProgress: "html-progress"
    of Feature.HtmlRequired: "html-required"
    of Feature.HtmlRole: "html-role"
    of Feature.HtmlRp: "html-rp"
    of Feature.HtmlRt: "html-rt"
    of Feature.HtmlRuby: "html-ruby"
    of Feature.HtmlSelect: "html-select"
    of Feature.HtmlSemantics: "html-semantics"
    of Feature.HtmlSmall: "html-small"
    of Feature.HtmlSpan: "html-span"
    of Feature.HtmlSrcset: "html-srcset"
    of Feature.HtmlStrike: "html-strike"
    of Feature.HtmlStrong: "html-strong"
    of Feature.HtmlStyle: "html-style"
    of Feature.HtmlSvg: "html-svg"
    of Feature.HtmlTable: "html-table"
    of Feature.HtmlTarget: "html-target"
    of Feature.HtmlTextarea: "html-textarea"
    of Feature.HtmlValign: "html-valign"
    of Feature.HtmlVideo: "html-video"
    of Feature.HtmlWbr: "html-wbr"
    of Feature.HtmlWidth: "html-width"
    of Feature.ImageAvif: "image-avif"
    of Feature.ImageBase64: "image-base64"
    of Feature.ImageBmp: "image-bmp"
    of Feature.ImageGif: "image-gif"
    of Feature.ImageIco: "image-ico"
    of Feature.ImageJpg: "image-jpg"
    of Feature.ImagePng: "image-png"
    of Feature.ImageSvg: "image-svg"
    of Feature.ImageWebp: "image-webp"
    of Feature.Unsupported: "unsupported"

func `%`*(v: Family): JsonNode =
  let str = case v:
    of Family.Aol: "aol"
    of Family.AppleMail: "apple-mail"
    of Family.Fastmail: "fastmail"
    of Family.FreeFr: "free-fr"
    of Family.Gmail: "gmail"
    of Family.Gmx: "gmx"
    of Family.Hey: "hey"
    of Family.Ionos1and1: "ionos-1and1"
    of Family.Laposte: "laposte"
    of Family.MailRu: "mail-ru"
    of Family.Microsoft: "microsoft"
    of Family.Orange: "orange"
    of Family.Outlook: "outlook"
    of Family.Protonmail: "protonmail"
    of Family.Rainloop: "rainloop"
    of Family.SamsungEmail: "samsung-email"
    of Family.Sfr: "sfr"
    of Family.TOnlineDe: "t-online-de"
    of Family.Thunderbird: "thunderbird"
    of Family.WebDe: "web-de"
    of Family.Yahoo: "yahoo"

  JsonNode(kind: JString, str: str)

func `$`*(v: Family): string =
  result = case v:
    of Family.Aol: "aol"
    of Family.AppleMail: "apple-mail"
    of Family.Fastmail: "fastmail"
    of Family.FreeFr: "free-fr"
    of Family.Gmail: "gmail"
    of Family.Gmx: "gmx"
    of Family.Hey: "hey"
    of Family.Ionos1and1: "ionos-1and1"
    of Family.Laposte: "laposte"
    of Family.MailRu: "mail-ru"
    of Family.Microsoft: "microsoft"
    of Family.Orange: "orange"
    of Family.Outlook: "outlook"
    of Family.Protonmail: "protonmail"
    of Family.Rainloop: "rainloop"
    of Family.SamsungEmail: "samsung-email"
    of Family.Sfr: "sfr"
    of Family.TOnlineDe: "t-online-de"
    of Family.Thunderbird: "thunderbird"
    of Family.WebDe: "web-de"
    of Family.Yahoo: "yahoo"
