#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type AttachmentMetaData* = object
  ## Meta data associated with an attachment. Attachments are stored as byte blobs so the meta data is stored separately.
  contentLength*: int64 ## Size of attachment in bytes
  contentType*: string ## Content type of attachment such as `image/png`
  id*: string ## ID of attachment
  name*: string ## Name of attachment if given
