#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_map

type `Method`* {.pure.} = enum
  GET
  HEAD
  POST
  PUT
  PATCH
  DELETE
  OPTIONS
  TRACE

type WebhookTestRequest* = object
  ## 
  url*: string
  `method`*: `Method`
  headers*: Table[string, string]
  payload*: string

func `%`*(v: `Method`): JsonNode =
  let str = case v:
    of `Method`.GET: "GET"
    of `Method`.HEAD: "HEAD"
    of `Method`.POST: "POST"
    of `Method`.PUT: "PUT"
    of `Method`.PATCH: "PATCH"
    of `Method`.DELETE: "DELETE"
    of `Method`.OPTIONS: "OPTIONS"
    of `Method`.TRACE: "TRACE"

  JsonNode(kind: JString, str: str)

func `$`*(v: `Method`): string =
  result = case v:
    of `Method`.GET: "GET"
    of `Method`.HEAD: "HEAD"
    of `Method`.POST: "POST"
    of `Method`.PUT: "PUT"
    of `Method`.PATCH: "PATCH"
    of `Method`.DELETE: "DELETE"
    of `Method`.OPTIONS: "OPTIONS"
    of `Method`.TRACE: "TRACE"
