#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type RecordTypes* {.pure.} = enum
  A
  NS
  MD
  MF
  CNAME
  SOA
  MB
  MG
  MR
  NULL
  WKS
  PTR
  HINFO
  MINFO
  MX
  TXT
  RP
  AFSDB
  X25
  ISDN
  RT
  NSAP
  NSAPPTR
  SIG
  KEY
  PX
  GPOS
  AAAA
  LOC
  NXT
  EID
  NIMLOC
  SRV
  ATMA
  NAPTR
  KX
  CERT
  A6
  DNAME
  SINK
  OPT
  APL
  DS
  SSHFP
  IPSECKEY
  RRSIG
  NSEC
  DNSKEY
  DHCID
  NSEC3
  NSEC3PARAM
  TLSA
  SMIMEA
  HIP
  NINFO
  RKEY
  TALINK
  CDS
  CDNSKEY
  OPENPGPKEY
  CSYNC
  ZONEMD
  SVCB
  HTTPS
  SPF
  UINFO
  UID
  GID
  UNSPEC
  NID
  L32
  L64
  LP
  EUI48
  EUI64
  TKEY
  TSIG
  IXFR
  AXFR
  MAILB
  MAILA
  ANY
  URI
  CAA
  AVC
  DOA
  AMTRELAY
  TA
  DLV

type DNSLookupOptions* = object
  ## Options for DNS query. 
  hostname*: string ## List of record types you wish to query such as MX, DNS, TXT, NS, A etc.
  omitFinalDNSDot*: bool ## Optionally control whether to omit the final dot in full DNS name values.
  recordTypes*: RecordTypes ## List of record types you wish to query such as MX, DNS, TXT, NS, A etc.

func `%`*(v: RecordTypes): JsonNode =
  let str = case v:
    of RecordTypes.A: "A"
    of RecordTypes.NS: "NS"
    of RecordTypes.MD: "MD"
    of RecordTypes.MF: "MF"
    of RecordTypes.CNAME: "CNAME"
    of RecordTypes.SOA: "SOA"
    of RecordTypes.MB: "MB"
    of RecordTypes.MG: "MG"
    of RecordTypes.MR: "MR"
    of RecordTypes.NULL: "NULL"
    of RecordTypes.WKS: "WKS"
    of RecordTypes.PTR: "PTR"
    of RecordTypes.HINFO: "HINFO"
    of RecordTypes.MINFO: "MINFO"
    of RecordTypes.MX: "MX"
    of RecordTypes.TXT: "TXT"
    of RecordTypes.RP: "RP"
    of RecordTypes.AFSDB: "AFSDB"
    of RecordTypes.X25: "X25"
    of RecordTypes.ISDN: "ISDN"
    of RecordTypes.RT: "RT"
    of RecordTypes.NSAP: "NSAP"
    of RecordTypes.NSAPPTR: "NSAP_PTR"
    of RecordTypes.SIG: "SIG"
    of RecordTypes.KEY: "KEY"
    of RecordTypes.PX: "PX"
    of RecordTypes.GPOS: "GPOS"
    of RecordTypes.AAAA: "AAAA"
    of RecordTypes.LOC: "LOC"
    of RecordTypes.NXT: "NXT"
    of RecordTypes.EID: "EID"
    of RecordTypes.NIMLOC: "NIMLOC"
    of RecordTypes.SRV: "SRV"
    of RecordTypes.ATMA: "ATMA"
    of RecordTypes.NAPTR: "NAPTR"
    of RecordTypes.KX: "KX"
    of RecordTypes.CERT: "CERT"
    of RecordTypes.A6: "A6"
    of RecordTypes.DNAME: "DNAME"
    of RecordTypes.SINK: "SINK"
    of RecordTypes.OPT: "OPT"
    of RecordTypes.APL: "APL"
    of RecordTypes.DS: "DS"
    of RecordTypes.SSHFP: "SSHFP"
    of RecordTypes.IPSECKEY: "IPSECKEY"
    of RecordTypes.RRSIG: "RRSIG"
    of RecordTypes.NSEC: "NSEC"
    of RecordTypes.DNSKEY: "DNSKEY"
    of RecordTypes.DHCID: "DHCID"
    of RecordTypes.NSEC3: "NSEC3"
    of RecordTypes.NSEC3PARAM: "NSEC3PARAM"
    of RecordTypes.TLSA: "TLSA"
    of RecordTypes.SMIMEA: "SMIMEA"
    of RecordTypes.HIP: "HIP"
    of RecordTypes.NINFO: "NINFO"
    of RecordTypes.RKEY: "RKEY"
    of RecordTypes.TALINK: "TALINK"
    of RecordTypes.CDS: "CDS"
    of RecordTypes.CDNSKEY: "CDNSKEY"
    of RecordTypes.OPENPGPKEY: "OPENPGPKEY"
    of RecordTypes.CSYNC: "CSYNC"
    of RecordTypes.ZONEMD: "ZONEMD"
    of RecordTypes.SVCB: "SVCB"
    of RecordTypes.HTTPS: "HTTPS"
    of RecordTypes.SPF: "SPF"
    of RecordTypes.UINFO: "UINFO"
    of RecordTypes.UID: "UID"
    of RecordTypes.GID: "GID"
    of RecordTypes.UNSPEC: "UNSPEC"
    of RecordTypes.NID: "NID"
    of RecordTypes.L32: "L32"
    of RecordTypes.L64: "L64"
    of RecordTypes.LP: "LP"
    of RecordTypes.EUI48: "EUI48"
    of RecordTypes.EUI64: "EUI64"
    of RecordTypes.TKEY: "TKEY"
    of RecordTypes.TSIG: "TSIG"
    of RecordTypes.IXFR: "IXFR"
    of RecordTypes.AXFR: "AXFR"
    of RecordTypes.MAILB: "MAILB"
    of RecordTypes.MAILA: "MAILA"
    of RecordTypes.ANY: "ANY"
    of RecordTypes.URI: "URI"
    of RecordTypes.CAA: "CAA"
    of RecordTypes.AVC: "AVC"
    of RecordTypes.DOA: "DOA"
    of RecordTypes.AMTRELAY: "AMTRELAY"
    of RecordTypes.TA: "TA"
    of RecordTypes.DLV: "DLV"

  JsonNode(kind: JString, str: str)

func `$`*(v: RecordTypes): string =
  result = case v:
    of RecordTypes.A: "A"
    of RecordTypes.NS: "NS"
    of RecordTypes.MD: "MD"
    of RecordTypes.MF: "MF"
    of RecordTypes.CNAME: "CNAME"
    of RecordTypes.SOA: "SOA"
    of RecordTypes.MB: "MB"
    of RecordTypes.MG: "MG"
    of RecordTypes.MR: "MR"
    of RecordTypes.NULL: "NULL"
    of RecordTypes.WKS: "WKS"
    of RecordTypes.PTR: "PTR"
    of RecordTypes.HINFO: "HINFO"
    of RecordTypes.MINFO: "MINFO"
    of RecordTypes.MX: "MX"
    of RecordTypes.TXT: "TXT"
    of RecordTypes.RP: "RP"
    of RecordTypes.AFSDB: "AFSDB"
    of RecordTypes.X25: "X25"
    of RecordTypes.ISDN: "ISDN"
    of RecordTypes.RT: "RT"
    of RecordTypes.NSAP: "NSAP"
    of RecordTypes.NSAPPTR: "NSAP_PTR"
    of RecordTypes.SIG: "SIG"
    of RecordTypes.KEY: "KEY"
    of RecordTypes.PX: "PX"
    of RecordTypes.GPOS: "GPOS"
    of RecordTypes.AAAA: "AAAA"
    of RecordTypes.LOC: "LOC"
    of RecordTypes.NXT: "NXT"
    of RecordTypes.EID: "EID"
    of RecordTypes.NIMLOC: "NIMLOC"
    of RecordTypes.SRV: "SRV"
    of RecordTypes.ATMA: "ATMA"
    of RecordTypes.NAPTR: "NAPTR"
    of RecordTypes.KX: "KX"
    of RecordTypes.CERT: "CERT"
    of RecordTypes.A6: "A6"
    of RecordTypes.DNAME: "DNAME"
    of RecordTypes.SINK: "SINK"
    of RecordTypes.OPT: "OPT"
    of RecordTypes.APL: "APL"
    of RecordTypes.DS: "DS"
    of RecordTypes.SSHFP: "SSHFP"
    of RecordTypes.IPSECKEY: "IPSECKEY"
    of RecordTypes.RRSIG: "RRSIG"
    of RecordTypes.NSEC: "NSEC"
    of RecordTypes.DNSKEY: "DNSKEY"
    of RecordTypes.DHCID: "DHCID"
    of RecordTypes.NSEC3: "NSEC3"
    of RecordTypes.NSEC3PARAM: "NSEC3PARAM"
    of RecordTypes.TLSA: "TLSA"
    of RecordTypes.SMIMEA: "SMIMEA"
    of RecordTypes.HIP: "HIP"
    of RecordTypes.NINFO: "NINFO"
    of RecordTypes.RKEY: "RKEY"
    of RecordTypes.TALINK: "TALINK"
    of RecordTypes.CDS: "CDS"
    of RecordTypes.CDNSKEY: "CDNSKEY"
    of RecordTypes.OPENPGPKEY: "OPENPGPKEY"
    of RecordTypes.CSYNC: "CSYNC"
    of RecordTypes.ZONEMD: "ZONEMD"
    of RecordTypes.SVCB: "SVCB"
    of RecordTypes.HTTPS: "HTTPS"
    of RecordTypes.SPF: "SPF"
    of RecordTypes.UINFO: "UINFO"
    of RecordTypes.UID: "UID"
    of RecordTypes.GID: "GID"
    of RecordTypes.UNSPEC: "UNSPEC"
    of RecordTypes.NID: "NID"
    of RecordTypes.L32: "L32"
    of RecordTypes.L64: "L64"
    of RecordTypes.LP: "LP"
    of RecordTypes.EUI48: "EUI48"
    of RecordTypes.EUI64: "EUI64"
    of RecordTypes.TKEY: "TKEY"
    of RecordTypes.TSIG: "TSIG"
    of RecordTypes.IXFR: "IXFR"
    of RecordTypes.AXFR: "AXFR"
    of RecordTypes.MAILB: "MAILB"
    of RecordTypes.MAILA: "MAILA"
    of RecordTypes.ANY: "ANY"
    of RecordTypes.URI: "URI"
    of RecordTypes.CAA: "CAA"
    of RecordTypes.AVC: "AVC"
    of RecordTypes.DOA: "DOA"
    of RecordTypes.AMTRELAY: "AMTRELAY"
    of RecordTypes.TA: "TA"
    of RecordTypes.DLV: "DLV"
