#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type Version* {.pure.} = enum
  STSv1

type Mode* {.pure.} = enum
  TESTING
  ENFORCE
  NONE

type GenerateMtaStsRecordOptions* = object
  ## 
  host*: string
  version*: Version
  mode*: Mode
  ttl*: int
  maxAgeSeconds*: int
  mxRecords*: seq[string]

func `%`*(v: Version): JsonNode =
  let str = case v:
    of Version.STSv1: "STSv1"

  JsonNode(kind: JString, str: str)

func `$`*(v: Version): string =
  result = case v:
    of Version.STSv1: "STSv1"

func `%`*(v: Mode): JsonNode =
  let str = case v:
    of Mode.TESTING: "TESTING"
    of Mode.ENFORCE: "ENFORCE"
    of Mode.NONE: "NONE"

  JsonNode(kind: JString, str: str)

func `$`*(v: Mode): string =
  result = case v:
    of Mode.TESTING: "TESTING"
    of Mode.ENFORCE: "ENFORCE"
    of Mode.NONE: "NONE"
