#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type SortDirection* {.pure.} = enum
  ASC
  DESC

type WaitForSingleSmsOptions* = object
  ## 
  phoneNumberId*: string
  timeout*: int64
  unreadOnly*: bool
  before*: string
  since*: string
  sortDirection*: SortDirection
  delay*: int64

func `%`*(v: SortDirection): JsonNode =
  let str = case v:
    of SortDirection.ASC: "ASC"
    of SortDirection.DESC: "DESC"

  JsonNode(kind: JString, str: str)

func `$`*(v: SortDirection): string =
  result = case v:
    of SortDirection.ASC: "ASC"
    of SortDirection.DESC: "DESC"
