#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type IsoCountryCode* {.pure.} = enum
  US
  GB
  AU

type CreateEmergencyAddressOptions* = object
  ## 
  customerName*: string
  address1*: string
  city*: string
  region*: string
  postalCode*: string
  isoCountryCode*: IsoCountryCode
  displayName*: string

func `%`*(v: IsoCountryCode): JsonNode =
  let str = case v:
    of IsoCountryCode.US: "US"
    of IsoCountryCode.GB: "GB"
    of IsoCountryCode.AU: "AU"

  JsonNode(kind: JString, str: str)

func `$`*(v: IsoCountryCode): string =
  result = case v:
    of IsoCountryCode.US: "US"
    of IsoCountryCode.GB: "GB"
    of IsoCountryCode.AU: "AU"
