#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type OutputFormat* {.pure.} = enum
  DEFAULT
  EXCEL

type ExportOptions* = object
  ## Options for exporting user data
  outputFormat*: OutputFormat
  excludePreviouslyExported*: bool
  createdEarliestTime*: string
  createdOldestTime*: string
  filter*: string
  listSeparatorToken*: string

func `%`*(v: OutputFormat): JsonNode =
  let str = case v:
    of OutputFormat.DEFAULT: "CSV_DEFAULT"
    of OutputFormat.EXCEL: "CSV_EXCEL"

  JsonNode(kind: JString, str: str)

func `$`*(v: OutputFormat): string =
  result = case v:
    of OutputFormat.DEFAULT: "CSV_DEFAULT"
    of OutputFormat.EXCEL: "CSV_EXCEL"
