#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_domain_name_record

type DomainDto* = object
  ## Domain plus verification records and status
  catchAllInboxId*: string ## The optional catch all inbox that will receive emails sent to the domain that cannot be matched.
  createdAt*: string
  dkimTokens*: seq[string] ## Unique token DKIM tokens
  domain*: string ## Custom domain name
  domainNameRecords*: seq[DomainNameRecord] ## List of DNS domain name records (C, MX, TXT) etc that you must add to the DNS server associated with your domain provider.
  id*: string
  isVerified*: bool ## Whether domain has been verified or not. If the domain is not verified after 72 hours there is most likely an issue with the domains DNS records.
  updatedAt*: string
  userId*: string
  verificationToken*: string ## Verification tokens
