#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type FlagOperation* {.pure.} = enum
  SETFLAGS
  ADDFLAGS
  REMOVEFLAGS

type ImapFlagOperationOptions* = object
  ## IMAP operation flags
  flagOperation*: FlagOperation
  flags*: seq[string]

func `%`*(v: FlagOperation): JsonNode =
  let str = case v:
    of FlagOperation.SETFLAGS: "SET_FLAGS"
    of FlagOperation.ADDFLAGS: "ADD_FLAGS"
    of FlagOperation.REMOVEFLAGS: "REMOVE_FLAGS"

  JsonNode(kind: JString, str: str)

func `$`*(v: FlagOperation): string =
  result = case v:
    of FlagOperation.SETFLAGS: "SET_FLAGS"
    of FlagOperation.ADDFLAGS: "ADD_FLAGS"
    of FlagOperation.REMOVEFLAGS: "REMOVE_FLAGS"
