#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type AliasDto* = object
  ## Email alias representation
  id*: string
  emailAddress*: string ## The alias's email address for receiving email
  maskedEmailAddress*: string ## The underlying email address that is hidden and will received forwarded email
  userId*: string
  inboxId*: string ## Inbox that is associated with the alias
  name*: string
  useThreads*: bool ## If alias will generate response threads or not when email are received by it
  isVerified*: bool ## Has the alias been verified. You must verify an alias if the masked email address has not yet been verified by your account
  createdAt*: string
  updatedAt*: string
