#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type ThreadProjection* = object
  ## A thread is a message thread created for a message received by an alias
  name*: string ## Name of thread
  id*: string ## ID of email thread
  subject*: string ## Thread subject
  inboxId*: string ## Inbox ID
  userId*: string ## User ID
  to*: seq[string] ## To recipients
  bcc*: seq[string] ## BCC recipients
  cc*: seq[string] ## CC recipients
  createdAt*: string ## Created at DateTime
  updatedAt*: string ## Updated at DateTime
  aliasId*: string ## Alias ID
