#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type Slug* {.pure.} = enum
  Aol
  AppleMail
  Fastmail
  FreeFr
  Gmail
  Gmx
  Hey
  Ionos1and1
  Laposte
  MailRu
  Microsoft
  Orange
  Outlook
  Protonmail
  Rainloop
  SamsungEmail
  Sfr
  TOnlineDe
  Thunderbird
  WebDe
  Yahoo

type EmailFeatureFamilyName* = object
  ## 
  slug*: Slug
  name*: string

func `%`*(v: Slug): JsonNode =
  let str = case v:
    of Slug.Aol: "aol"
    of Slug.AppleMail: "apple-mail"
    of Slug.Fastmail: "fastmail"
    of Slug.FreeFr: "free-fr"
    of Slug.Gmail: "gmail"
    of Slug.Gmx: "gmx"
    of Slug.Hey: "hey"
    of Slug.Ionos1and1: "ionos-1and1"
    of Slug.Laposte: "laposte"
    of Slug.MailRu: "mail-ru"
    of Slug.Microsoft: "microsoft"
    of Slug.Orange: "orange"
    of Slug.Outlook: "outlook"
    of Slug.Protonmail: "protonmail"
    of Slug.Rainloop: "rainloop"
    of Slug.SamsungEmail: "samsung-email"
    of Slug.Sfr: "sfr"
    of Slug.TOnlineDe: "t-online-de"
    of Slug.Thunderbird: "thunderbird"
    of Slug.WebDe: "web-de"
    of Slug.Yahoo: "yahoo"

  JsonNode(kind: JString, str: str)

func `$`*(v: Slug): string =
  result = case v:
    of Slug.Aol: "aol"
    of Slug.AppleMail: "apple-mail"
    of Slug.Fastmail: "fastmail"
    of Slug.FreeFr: "free-fr"
    of Slug.Gmail: "gmail"
    of Slug.Gmx: "gmx"
    of Slug.Hey: "hey"
    of Slug.Ionos1and1: "ionos-1and1"
    of Slug.Laposte: "laposte"
    of Slug.MailRu: "mail-ru"
    of Slug.Microsoft: "microsoft"
    of Slug.Orange: "orange"
    of Slug.Outlook: "outlook"
    of Slug.Protonmail: "protonmail"
    of Slug.Rainloop: "rainloop"
    of Slug.SamsungEmail: "samsung-email"
    of Slug.Sfr: "sfr"
    of Slug.TOnlineDe: "t-online-de"
    of Slug.Thunderbird: "thunderbird"
    of Slug.WebDe: "web-de"
    of Slug.Yahoo: "yahoo"
