#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_match_option

type CountType* {.pure.} = enum
  EXACTLY
  ATLEAST

type SortDirection* {.pure.} = enum
  ASC
  DESC

type WaitForConditions* = object
  ## Conditions that a `waitForXEmails` endpoint operates on. The methods wait until given conditions are met or a timeout is reached. If the conditions are met without needing to wait the results will be returned immediately. Can include `unreadOnly` to ignore already read emails that were returned in an API call or viewing in the dashboard. Can also include matches for emails containing `from`, `subject`, `hasAttachments` etc.
  count*: int ## Number of results that should match conditions. Either exactly or at least this amount based on the `countType`. If count condition is not met and the timeout has not been reached the `waitFor` method will retry the operation.
  countType*: CountType ## How should the found count be compared to the expected count.
  inboxId*: string ## ID of inbox to search within and apply conditions to. Essentially filtering the emails found to give a count.
  matches*: seq[MatchOption] ## Conditions that should be matched for an email to qualify for results. Each condition will be applied in order to each email within an inbox to filter a result list of matching emails you are waiting for.
  sortDirection*: SortDirection ## Direction to sort matching emails by created time
  timeout*: int64 ## Max time in milliseconds to retry the `waitFor` operation until conditions are met.
  unreadOnly*: bool ## Apply conditions only to **unread** emails. All emails begin with `read=false`. An email is marked `read=true` when an `EmailDto` representation of it has been returned to the user at least once. For example you have called `getEmail` or `waitForLatestEmail` etc., or you have viewed the email in the dashboard. 

func `%`*(v: CountType): JsonNode =
  let str = case v:
    of CountType.EXACTLY: "EXACTLY"
    of CountType.ATLEAST: "ATLEAST"

  JsonNode(kind: JString, str: str)

func `$`*(v: CountType): string =
  result = case v:
    of CountType.EXACTLY: "EXACTLY"
    of CountType.ATLEAST: "ATLEAST"

func `%`*(v: SortDirection): JsonNode =
  let str = case v:
    of SortDirection.ASC: "ASC"
    of SortDirection.DESC: "DESC"

  JsonNode(kind: JString, str: str)

func `$`*(v: SortDirection): string =
  result = case v:
    of SortDirection.ASC: "ASC"
    of SortDirection.DESC: "DESC"
