#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_email_analysis
import model_email_recipients
import model_map
import model_sender

type Email* = object
  ## Email entity (also known as EmailDto). When an SMTP email message is received by MailSlurp it is parsed. The body and attachments are written to disk and the fields such as to, from, subject etc are stored in a database. The `body` contains the email content. If you want the original SMTP message see the `getRawEmail` endpoints. The attachments can be fetched using the AttachmentController
  analysis*: EmailAnalysis
  attachments*: seq[string] ## List of IDs of attachments found in the email. Use these IDs with the Inbox and Email Controllers to download attachments and attachment meta data such as filesize, name, extension.
  bcc*: seq[string] ## List of `BCC` recipients email addresses that the email was addressed to. See recipients object for names.
  body*: string ## The body of the email message as text parsed from the SMTP message body (does not include attachments). Fetch the raw content to access the SMTP message and use the attachments property to access attachments. The body is stored separately to the email entity so the body is not returned in paginated results only in full single email or wait requests.
  bodyExcerpt*: string ## An excerpt of the body of the email message for quick preview .
  bodyMD5Hash*: string ## A hash signature of the email message using MD5. Useful for comparing emails without fetching full body.
  cc*: seq[string] ## List of `CC` recipients email addresses that the email was addressed to. See recipients object for names.
  charset*: string ## Detected character set of the email body such as UTF-8
  createdAt*: string ## When was the email received by MailSlurp
  `from`*: string ## Who the email was sent from. An email address - see fromName for the sender name.
  headers*: Table[string, string] ## Collection of SMTP headers attached to email
  id*: string ## ID of the email entity
  inboxId*: string ## ID of the inbox that received the email
  isHTML*: bool ## Is the email body HTML
  read*: bool ## Read flag. Has the email ever been viewed in the dashboard or fetched via the API with a hydrated body? If so the email is marked as read. Paginated results do not affect read status. Read status is different to email opened event as it depends on your own account accessing the email. Email opened is determined by tracking pixels sent to other uses if enable during sending. You can listened for both email read and email opened events using webhooks.
  recipients*: EmailRecipients
  replyTo*: string ## The `replyTo` field on the received email message
  sender*: Sender
  subject*: string ## The subject line of the email message as specified by SMTP subject header
  teamAccess*: bool ## Can the email be accessed by organization team members
  to*: seq[string] ## List of `To` recipient email addresses that the email was addressed to. See recipients object for names.
  updatedAt*: string ## When was the email last updated
  userId*: string ## ID of user that email belongs to
