#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type SimpleSendEmailOptions* = object
  ## 
  body*: string ## Body of the email message. Supports HTML
  senderId*: string ## ID of inbox to send from. If null an inbox will be created for sending
  subject*: string ## Subject line of the email
  to*: string ## Email address to send to
