#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type UserType* {.pure.} = enum
  SOLO
  CHILDSOLO
  CHILDTEAM

type Verified* {.pure.} = enum
  VERIFIED
  PENDING

type UserDto* = object
  ## Representation a user's account
  id*: string
  apiKey*: string
  emailAddress*: string
  emailAddressMd5*: string
  created*: string
  userType*: UserType
  organization*: string ## Does user belong to an organization
  verified*: Verified ## Has user accepted an organization invite
  hasPassword*: bool
  isFrozen*: bool
  addNewContacts*: bool
  ssoProvider*: string
  customerId*: string
  hasOnboarded*: bool
  imapUsername*: string
  imapPassword*: string
  smtpUsername*: string
  smtpPassword*: string

func `%`*(v: UserType): JsonNode =
  let str = case v:
    of UserType.SOLO: "SOLO"
    of UserType.CHILDSOLO: "CHILD_SOLO"
    of UserType.CHILDTEAM: "CHILD_TEAM"

  JsonNode(kind: JString, str: str)

func `$`*(v: UserType): string =
  result = case v:
    of UserType.SOLO: "SOLO"
    of UserType.CHILDSOLO: "CHILD_SOLO"
    of UserType.CHILDTEAM: "CHILD_TEAM"

func `%`*(v: Verified): JsonNode =
  let str = case v:
    of Verified.VERIFIED: "VERIFIED"
    of Verified.PENDING: "PENDING"

  JsonNode(kind: JString, str: str)

func `$`*(v: Verified): string =
  result = case v:
    of Verified.VERIFIED: "VERIFIED"
    of Verified.PENDING: "PENDING"
