#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import json
import tables


type ConnectorType* {.pure.} = enum
  IMAP

type SyncScheduleType* {.pure.} = enum
  INTERVAL

type ConnectorProjection* = object
  ## Connector
  id*: string
  inboxId*: string
  userId*: string
  createdAt*: string
  connectorType*: ConnectorType
  syncScheduleType*: SyncScheduleType
  syncInterval*: int
  syncEnabled*: bool

func `%`*(v: ConnectorType): JsonNode =
  let str = case v:
    of ConnectorType.IMAP: "IMAP"

  JsonNode(kind: JString, str: str)

func `$`*(v: ConnectorType): string =
  result = case v:
    of ConnectorType.IMAP: "IMAP"

func `%`*(v: SyncScheduleType): JsonNode =
  let str = case v:
    of SyncScheduleType.INTERVAL: "INTERVAL"

  JsonNode(kind: JString, str: str)

func `$`*(v: SyncScheduleType): string =
  result = case v:
    of SyncScheduleType.INTERVAL: "INTERVAL"
