#
# MailSlurp API
# 
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# The version of the OpenAPI document: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_create_template_options
import ../models/model_page_template_projection
import ../models/model_template_dto
import ../models/model_template_preview
import ../models/model_template_projection

const basepath = "https://api.mailslurp.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      when name(stripGenericParams(T.typedesc).typedesc) == name(Table):
        (some(json.to(parseJson(response.body), T.typedesc)), response)
      else:
        (some(marshal.to[T](response.body)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc createTemplate*(httpClient: HttpClient, CreateTemplateOptions: CreateTemplateOptions): (Option[TemplateDto], Response) =
  ## Create a Template
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/templates", $(%CreateTemplateOptions))
  constructResult[TemplateDto](response)


proc deleteTemplate*(httpClient: HttpClient, templateId: string): Response =
  ## Delete email template
  httpClient.delete(basepath & fmt"/templates/{templateId}")


proc getAllTemplates*(httpClient: HttpClient, page: int, size: int, sort: string, since: string, before: string): (Option[PageTemplateProjection], Response) =
  ## List templates
  let query_for_api_call = encodeQuery([
    ("page", $page), # Optional page index in list pagination
    ("size", $size), # Optional page size in list pagination
    ("sort", $sort), # Optional createdAt sort direction ASC or DESC
    ("since", $since), # Filter by created at after the given timestamp
    ("before", $before), # Filter by created at before the given timestamp
  ])

  let response = httpClient.get(basepath & "/templates/paginated" & "?" & query_for_api_call)
  constructResult[PageTemplateProjection](response)


proc getTemplate*(httpClient: HttpClient, templateId: string): (Option[TemplateDto], Response) =
  ## Get template

  let response = httpClient.get(basepath & fmt"/templates/{templateId}")
  constructResult[TemplateDto](response)


proc getTemplatePreviewHtml*(httpClient: HttpClient, templateId: string): (Option[string], Response) =
  ## Get template preview HTML

  let response = httpClient.get(basepath & fmt"/templates/{templateId}/preview/html")
  constructResult[string](response)


proc getTemplatePreviewJson*(httpClient: HttpClient, templateId: string): (Option[TemplatePreview], Response) =
  ## Get template preview Json

  let response = httpClient.get(basepath & fmt"/templates/{templateId}/preview/json")
  constructResult[TemplatePreview](response)


proc getTemplates*(httpClient: HttpClient): (Option[seq[TemplateProjection]], Response) =
  ## List templates

  let response = httpClient.get(basepath & "/templates")
  constructResult[seq[TemplateProjection]](response)


proc updateTemplate*(httpClient: HttpClient, templateId: string, CreateTemplateOptions: CreateTemplateOptions): (Option[TemplateDto], Response) =
  ## Update template
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.put(basepath & fmt"/templates/{templateId}", $(%CreateTemplateOptions))
  constructResult[TemplateDto](response)

